// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VTOP_H_
#define VERILATED_VTOP_H_  // guard

#include "verilated_heavy.h"

//==========

class Vtop__Syms;
class Vtop_VerilatedVcd;


//----------

VL_MODULE(Vtop) {
  public:
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(sys_clk,0,0);
    VL_IN8(sys_rst,0,0);
    VL_IN8(serial_rx,0,0);
    VL_OUT8(serial_tx,0,0);
    VL_OUT8(spiflash_cs_n,0,0);
    VL_OUT8(spiflash_clk,0,0);
    VL_IN8(spiflash_miso,0,0);
    VL_OUT8(spiflash_mosi,0,0);
    VL_IN8(spiflash_wp,0,0);
    VL_IN8(spiflash_hold,0,0);
    VL_IN8(serial_dbg_rx,0,0);
    VL_OUT8(serial_dbg_tx,0,0);
    VL_OUT8(gpio_out_pad,0,0);
    VL_IN8(gpio_in_pad,0,0);
    VL_OUT8(gpio_outenb_pad,0,0);
    VL_OUT8(gpio_inenb_pad,0,0);
    VL_OUT8(gpio_mode0_pad,0,0);
    VL_OUT8(gpio_mode1_pad,0,0);
    VL_OUT8(mprj_wb_iena,0,0);
    VL_OUT8(user_irq_ena,2,0);
    VL_OUTW(la_output,127,0,4);
    VL_INW(la_input,127,0,4);
    VL_OUTW(la_oenb,127,0,4);
    VL_OUTW(la_iena,127,0,4);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ top__DOT__int_rst;
        CData/*0:0*/ top__DOT__mgmtsoc_soc_rst;
        CData/*1:0*/ top__DOT__mgmtsoc_reset_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_reset_re;
        CData/*0:0*/ top__DOT__mgmtsoc_scratch_re;
        CData/*0:0*/ top__DOT__mgmtsoc_bus_errors_re;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv32_trap;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv32_idbus_ack;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv32_mem_valid;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv32_mem_instr;
        CData/*3:0*/ top__DOT__mgmtsoc_picorv32_mem_wstrb;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv320;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv321;
        CData/*3:0*/ top__DOT__mgmtsoc_picorv324;
        CData/*0:0*/ top__DOT__mgmtsoc_picorv325;
        CData/*0:0*/ top__DOT__mgmtsoc_tx_sink_ready;
        CData/*7:0*/ top__DOT__mgmtsoc_tx_data;
        CData/*3:0*/ top__DOT__mgmtsoc_tx_count;
        CData/*0:0*/ top__DOT__mgmtsoc_tx_enable;
        CData/*0:0*/ top__DOT__mgmtsoc_tx_tick;
        CData/*0:0*/ top__DOT__mgmtsoc_rx_source_valid;
        CData/*7:0*/ top__DOT__mgmtsoc_rx_source_payload_data;
        CData/*7:0*/ top__DOT__mgmtsoc_rx_data;
        CData/*3:0*/ top__DOT__mgmtsoc_rx_count;
        CData/*0:0*/ top__DOT__mgmtsoc_rx_enable;
        CData/*0:0*/ top__DOT__mgmtsoc_rx_tick;
        CData/*0:0*/ top__DOT__mgmtsoc_rx_rx_d;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rxtx_re;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rxtx_we;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_txfull_re;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rxempty_re;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_pending;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_clear;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_trigger_d;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_pending;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_clear;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_trigger_d;
        CData/*1:0*/ top__DOT__mgmtsoc_uart_status_status;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_status_re;
        CData/*1:0*/ top__DOT__mgmtsoc_uart_pending_status;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_pending_re;
        CData/*1:0*/ top__DOT__mgmtsoc_uart_pending_r;
        CData/*1:0*/ top__DOT__mgmtsoc_uart_enable_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_enable_re;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_txempty_re;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rxfull_re;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_fifo_readable;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_fifo_syncfifo_writable;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_fifo_syncfifo_re;
        CData/*4:0*/ top__DOT__mgmtsoc_uart_tx_fifo_level0;
        CData/*3:0*/ top__DOT__mgmtsoc_uart_tx_fifo_produce;
        CData/*3:0*/ top__DOT__mgmtsoc_uart_tx_fifo_consume;
        CData/*3:0*/ top__DOT__mgmtsoc_uart_tx_fifo_wrport_adr;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_tx_fifo_do_read;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_fifo_readable;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_fifo_syncfifo_writable;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_fifo_syncfifo_re;
        CData/*4:0*/ top__DOT__mgmtsoc_uart_rx_fifo_level0;
        CData/*3:0*/ top__DOT__mgmtsoc_uart_rx_fifo_produce;
        CData/*3:0*/ top__DOT__mgmtsoc_uart_rx_fifo_consume;
        CData/*3:0*/ top__DOT__mgmtsoc_uart_rx_fifo_wrport_adr;
        CData/*0:0*/ top__DOT__mgmtsoc_uart_rx_fifo_do_read;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_load_re;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_reload_re;
    };
    struct {
        CData/*0:0*/ top__DOT__mgmtsoc_timer_en_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_en_re;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_update_value_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_update_value_re;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_value_re;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_zero_pending;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_zero_clear;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_zero_trigger_d;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_status_re;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_pending_re;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_pending_r;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_enable_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_timer_enable_re;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_source_valid;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_source_last;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_sink_ready;
        CData/*7:0*/ top__DOT__mgmtsoc_litespisdrphycore_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_re;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_negedge;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_en;
        CData/*7:0*/ top__DOT__mgmtsoc_litespisdrphycore_cnt;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_clk;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_posedge_reg;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_posedge_reg2;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_done;
        CData/*3:0*/ top__DOT__mgmtsoc_litespisdrphycore_count;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_dq_o;
        CData/*1:0*/ top__DOT__mgmtsoc_litespisdrphycore_dq_i;
        CData/*7:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_cnt;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_out_load;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_out_shift;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_in_shift;
        CData/*0:0*/ top__DOT__mgmtsoc_crossbar_cs;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_source_valid;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_source_last;
        CData/*5:0*/ top__DOT__mgmtsoc_litespimmap_source_payload_len;
        CData/*3:0*/ top__DOT__mgmtsoc_litespimmap_source_payload_width;
        CData/*7:0*/ top__DOT__mgmtsoc_litespimmap_source_payload_mask;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_sink_ready;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_bus_cyc;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_bus_ack;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_cs;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_burst_cs;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_wait;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_done;
        CData/*7:0*/ top__DOT__mgmtsoc_litespimmap_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_re;
        CData/*0:0*/ top__DOT__mgmtsoc_master_cs_storage;
        CData/*0:0*/ top__DOT__mgmtsoc_master_cs_re;
        CData/*0:0*/ top__DOT__mgmtsoc_master_phyconfig_re;
        CData/*0:0*/ top__DOT__mgmtsoc_master_rxtx_re;
        CData/*0:0*/ top__DOT__mgmtsoc_master_rxtx_we;
        CData/*1:0*/ top__DOT__mgmtsoc_master_status_status;
        CData/*0:0*/ top__DOT__mgmtsoc_master_status_re;
        CData/*0:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_valid;
        CData/*0:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_first;
        CData/*0:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_last;
        CData/*5:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_payload_len;
        CData/*3:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_payload_width;
        CData/*7:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_payload_mask;
        CData/*0:0*/ top__DOT__mgmtsoc_master_rx_fifo_source_valid;
        CData/*0:0*/ top__DOT__mgmtsoc_master_rx_fifo_source_first;
        CData/*0:0*/ top__DOT__mgmtsoc_master_rx_fifo_source_last;
        CData/*0:0*/ top__DOT__uart_bridge_tx_sink_valid;
    };
    struct {
        CData/*0:0*/ top__DOT__uart_bridge_tx_sink_ready;
        CData/*7:0*/ top__DOT__uart_bridge_tx_sink_payload_data;
        CData/*7:0*/ top__DOT__uart_bridge_tx_data;
        CData/*3:0*/ top__DOT__uart_bridge_tx_count;
        CData/*0:0*/ top__DOT__uart_bridge_tx_enable;
        CData/*0:0*/ top__DOT__uart_bridge_tx_tick;
        CData/*0:0*/ top__DOT__uart_bridge_rx_source_valid;
        CData/*0:0*/ top__DOT__uart_bridge_rx_source_ready;
        CData/*7:0*/ top__DOT__uart_bridge_rx_source_payload_data;
        CData/*7:0*/ top__DOT__uart_bridge_rx_data;
        CData/*3:0*/ top__DOT__uart_bridge_rx_count;
        CData/*0:0*/ top__DOT__uart_bridge_rx_enable;
        CData/*0:0*/ top__DOT__uart_bridge_rx_tick;
        CData/*0:0*/ top__DOT__uart_bridge_rx_rx_d;
        CData/*0:0*/ top__DOT__uart_bridge_wishbone_cyc;
        CData/*0:0*/ top__DOT__uart_bridge_wishbone_stb;
        CData/*0:0*/ top__DOT__uart_bridge_wishbone_ack;
        CData/*0:0*/ top__DOT__uart_bridge_wishbone_we;
        CData/*7:0*/ top__DOT__uart_bridge_cmd;
        CData/*0:0*/ top__DOT__uart_bridge_incr;
        CData/*7:0*/ top__DOT__uart_bridge_length;
        CData/*1:0*/ top__DOT__uart_bridge_bytes_count;
        CData/*7:0*/ top__DOT__uart_bridge_words_count;
        CData/*0:0*/ top__DOT__uart_bridge_done;
        CData/*0:0*/ top__DOT__uart_bridge_is_ongoing;
        CData/*0:0*/ top__DOT__gpio_mode1_storage;
        CData/*0:0*/ top__DOT__gpio_mode1_re;
        CData/*0:0*/ top__DOT__gpio_mode0_storage;
        CData/*0:0*/ top__DOT__gpio_mode0_re;
        CData/*0:0*/ top__DOT__gpio_ien_storage;
        CData/*0:0*/ top__DOT__gpio_ien_re;
        CData/*0:0*/ top__DOT__gpio_oe_storage;
        CData/*0:0*/ top__DOT__gpio_oe_re;
        CData/*0:0*/ top__DOT__gpio_in_re;
        CData/*0:0*/ top__DOT__gpio_out_storage;
        CData/*0:0*/ top__DOT__gpio_out_re;
        CData/*0:0*/ top__DOT__la_ien_re;
        CData/*0:0*/ top__DOT__la_oe_re;
        CData/*0:0*/ top__DOT__la_in_re;
        CData/*0:0*/ top__DOT__la_out_re;
        CData/*0:0*/ top__DOT__mprj_wb_iena_storage;
        CData/*0:0*/ top__DOT__mprj_wb_iena_re;
        CData/*2:0*/ top__DOT__user_irq_ena_storage;
        CData/*0:0*/ top__DOT__user_irq_ena_re;
        CData/*0:0*/ top__DOT__rs232phy_rs232phytx_state;
        CData/*0:0*/ top__DOT__rs232phy_rs232phytx_next_state;
        CData/*3:0*/ top__DOT__mgmtsoc_tx_count_rs232phy_rs232phytx_next_value0;
        CData/*0:0*/ top__DOT__mgmtsoc_tx_count_rs232phy_rs232phytx_next_value_ce0;
        CData/*0:0*/ top__DOT__mgmtsoc_serial_tx_rs232phy_rs232phytx_next_value1;
        CData/*0:0*/ top__DOT__mgmtsoc_serial_tx_rs232phy_rs232phytx_next_value_ce1;
        CData/*7:0*/ top__DOT__mgmtsoc_tx_data_rs232phy_rs232phytx_next_value2;
        CData/*0:0*/ top__DOT__mgmtsoc_tx_data_rs232phy_rs232phytx_next_value_ce2;
        CData/*0:0*/ top__DOT__rs232phy_rs232phyrx_state;
        CData/*0:0*/ top__DOT__rs232phy_rs232phyrx_next_state;
        CData/*3:0*/ top__DOT__mgmtsoc_rx_count_rs232phy_rs232phyrx_next_value0;
        CData/*0:0*/ top__DOT__mgmtsoc_rx_count_rs232phy_rs232phyrx_next_value_ce0;
        CData/*7:0*/ top__DOT__mgmtsoc_rx_data_rs232phy_rs232phyrx_next_value1;
        CData/*0:0*/ top__DOT__mgmtsoc_rx_data_rs232phy_rs232phyrx_next_value_ce1;
        CData/*1:0*/ top__DOT__litespiphy_state;
        CData/*1:0*/ top__DOT__litespiphy_next_state;
        CData/*7:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_cnt_litespiphy_next_value;
        CData/*0:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_cnt_litespiphy_next_value_ce;
        CData/*1:0*/ top__DOT__litespi_request;
        CData/*0:0*/ top__DOT__litespi_grant;
    };
    struct {
        CData/*0:0*/ top__DOT__litespi_tx_mux_source_valid;
        CData/*0:0*/ top__DOT__litespi_tx_mux_source_first;
        CData/*0:0*/ top__DOT__litespi_tx_mux_source_last;
        CData/*5:0*/ top__DOT__litespi_tx_mux_source_payload_len;
        CData/*3:0*/ top__DOT__litespi_tx_mux_source_payload_width;
        CData/*7:0*/ top__DOT__litespi_tx_mux_source_payload_mask;
        CData/*0:0*/ top__DOT__litespi_tx_mux_endpoint0_sink_ready;
        CData/*0:0*/ top__DOT__litespi_tx_mux_endpoint1_sink_ready;
        CData/*0:0*/ top__DOT__litespi_rx_demux_sink_ready;
        CData/*0:0*/ top__DOT__litespi_rx_demux_endpoint0_source_valid;
        CData/*0:0*/ top__DOT__litespi_rx_demux_endpoint0_source_first;
        CData/*0:0*/ top__DOT__litespi_rx_demux_endpoint0_source_last;
        CData/*0:0*/ top__DOT__litespi_rx_demux_endpoint1_source_valid;
        CData/*0:0*/ top__DOT__litespi_rx_demux_endpoint1_source_first;
        CData/*0:0*/ top__DOT__litespi_rx_demux_endpoint1_source_last;
        CData/*3:0*/ top__DOT__litespi_state;
        CData/*3:0*/ top__DOT__litespi_next_state;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_burst_cs_litespi_next_value0;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_burst_cs_litespi_next_value_ce0;
        CData/*0:0*/ top__DOT__mgmtsoc_litespimmap_burst_adr_litespi_next_value_ce1;
        CData/*0:0*/ top__DOT__uartwishbonebridge_rs232phytx_state;
        CData/*0:0*/ top__DOT__uartwishbonebridge_rs232phytx_next_state;
        CData/*3:0*/ top__DOT__uart_bridge_tx_count_uartwishbonebridge_rs232phytx_next_value0;
        CData/*0:0*/ top__DOT__uart_bridge_tx_count_uartwishbonebridge_rs232phytx_next_value_ce0;
        CData/*0:0*/ top__DOT__obj_serial_dbg_tx_uartwishbonebridge_rs232phytx_next_value1;
        CData/*0:0*/ top__DOT__obj_serial_dbg_tx_uartwishbonebridge_rs232phytx_next_value_ce1;
        CData/*7:0*/ top__DOT__uart_bridge_tx_data_uartwishbonebridge_rs232phytx_next_value2;
        CData/*0:0*/ top__DOT__uart_bridge_tx_data_uartwishbonebridge_rs232phytx_next_value_ce2;
        CData/*0:0*/ top__DOT__uartwishbonebridge_rs232phyrx_state;
        CData/*0:0*/ top__DOT__uartwishbonebridge_rs232phyrx_next_state;
        CData/*3:0*/ top__DOT__uart_bridge_rx_count_uartwishbonebridge_rs232phyrx_next_value0;
        CData/*0:0*/ top__DOT__uart_bridge_rx_count_uartwishbonebridge_rs232phyrx_next_value_ce0;
        CData/*7:0*/ top__DOT__uart_bridge_rx_data_uartwishbonebridge_rs232phyrx_next_value1;
        CData/*0:0*/ top__DOT__uart_bridge_rx_data_uartwishbonebridge_rs232phyrx_next_value_ce1;
        CData/*2:0*/ top__DOT__uartwishbonebridge_state;
        CData/*2:0*/ top__DOT__uartwishbonebridge_next_state;
        CData/*1:0*/ top__DOT__uart_bridge_bytes_count_uartwishbonebridge_next_value0;
        CData/*0:0*/ top__DOT__uart_bridge_bytes_count_uartwishbonebridge_next_value_ce0;
        CData/*7:0*/ top__DOT__uart_bridge_words_count_uartwishbonebridge_next_value1;
        CData/*0:0*/ top__DOT__uart_bridge_words_count_uartwishbonebridge_next_value_ce1;
        CData/*7:0*/ top__DOT__uart_bridge_cmd_uartwishbonebridge_next_value2;
        CData/*0:0*/ top__DOT__uart_bridge_cmd_uartwishbonebridge_next_value_ce2;
        CData/*7:0*/ top__DOT__uart_bridge_length_uartwishbonebridge_next_value3;
        CData/*0:0*/ top__DOT__uart_bridge_length_uartwishbonebridge_next_value_ce3;
        CData/*0:0*/ top__DOT__uart_bridge_address_uartwishbonebridge_next_value_ce4;
        CData/*0:0*/ top__DOT__uart_bridge_incr_uartwishbonebridge_next_value5;
        CData/*0:0*/ top__DOT__uart_bridge_incr_uartwishbonebridge_next_value_ce5;
        CData/*0:0*/ top__DOT__uart_bridge_data_uartwishbonebridge_next_value_ce6;
        CData/*0:0*/ top__DOT__mgmtsoc_we;
        CData/*0:0*/ top__DOT__mgmtsoc_wishbone_cyc;
        CData/*0:0*/ top__DOT__mgmtsoc_wishbone_ack;
        CData/*0:0*/ top__DOT__shared_ack;
        CData/*1:0*/ top__DOT__request;
        CData/*0:0*/ top__DOT__grant;
        CData/*1:0*/ top__DOT__slave_sel;
        CData/*1:0*/ top__DOT__slave_sel_r;
        CData/*0:0*/ top__DOT__error;
        CData/*0:0*/ top__DOT__done;
        CData/*0:0*/ top__DOT__csrbank0_reset0_re;
        CData/*0:0*/ top__DOT__csrbank0_reset0_we;
        CData/*0:0*/ top__DOT__csrbank0_scratch0_re;
        CData/*0:0*/ top__DOT__csrbank0_scratch0_we;
        CData/*0:0*/ top__DOT__csrbank0_bus_errors_re;
        CData/*0:0*/ top__DOT__csrbank0_bus_errors_we;
    };
    struct {
        CData/*0:0*/ top__DOT__csrbank1_mode10_re;
        CData/*0:0*/ top__DOT__csrbank1_mode10_we;
        CData/*0:0*/ top__DOT__csrbank1_mode00_re;
        CData/*0:0*/ top__DOT__csrbank1_mode00_we;
        CData/*0:0*/ top__DOT__csrbank1_ien0_re;
        CData/*0:0*/ top__DOT__csrbank1_ien0_we;
        CData/*0:0*/ top__DOT__csrbank1_oe0_re;
        CData/*0:0*/ top__DOT__csrbank1_oe0_we;
        CData/*0:0*/ top__DOT__csrbank1_in_re;
        CData/*0:0*/ top__DOT__csrbank1_in_we;
        CData/*0:0*/ top__DOT__csrbank1_out0_re;
        CData/*0:0*/ top__DOT__csrbank1_out0_we;
        CData/*0:0*/ top__DOT__csrbank2_ien3_re;
        CData/*0:0*/ top__DOT__csrbank2_ien3_we;
        CData/*0:0*/ top__DOT__csrbank2_ien2_re;
        CData/*0:0*/ top__DOT__csrbank2_ien2_we;
        CData/*0:0*/ top__DOT__csrbank2_ien1_re;
        CData/*0:0*/ top__DOT__csrbank2_ien1_we;
        CData/*0:0*/ top__DOT__csrbank2_ien0_re;
        CData/*0:0*/ top__DOT__csrbank2_ien0_we;
        CData/*0:0*/ top__DOT__csrbank2_oe3_re;
        CData/*0:0*/ top__DOT__csrbank2_oe3_we;
        CData/*0:0*/ top__DOT__csrbank2_oe2_re;
        CData/*0:0*/ top__DOT__csrbank2_oe2_we;
        CData/*0:0*/ top__DOT__csrbank2_oe1_re;
        CData/*0:0*/ top__DOT__csrbank2_oe1_we;
        CData/*0:0*/ top__DOT__csrbank2_oe0_re;
        CData/*0:0*/ top__DOT__csrbank2_oe0_we;
        CData/*0:0*/ top__DOT__csrbank2_in3_re;
        CData/*0:0*/ top__DOT__csrbank2_in3_we;
        CData/*0:0*/ top__DOT__csrbank2_in2_re;
        CData/*0:0*/ top__DOT__csrbank2_in2_we;
        CData/*0:0*/ top__DOT__csrbank2_in1_re;
        CData/*0:0*/ top__DOT__csrbank2_in1_we;
        CData/*0:0*/ top__DOT__csrbank2_in0_re;
        CData/*0:0*/ top__DOT__csrbank2_in0_we;
        CData/*0:0*/ top__DOT__csrbank2_out3_re;
        CData/*0:0*/ top__DOT__csrbank2_out3_we;
        CData/*0:0*/ top__DOT__csrbank2_out2_re;
        CData/*0:0*/ top__DOT__csrbank2_out2_we;
        CData/*0:0*/ top__DOT__csrbank2_out1_re;
        CData/*0:0*/ top__DOT__csrbank2_out1_we;
        CData/*0:0*/ top__DOT__csrbank2_out0_re;
        CData/*0:0*/ top__DOT__csrbank2_out0_we;
        CData/*0:0*/ top__DOT__csrbank3_out0_re;
        CData/*0:0*/ top__DOT__csrbank3_out0_we;
        CData/*0:0*/ top__DOT__csrbank4_mmap_dummy_bits0_re;
        CData/*0:0*/ top__DOT__csrbank4_mmap_dummy_bits0_we;
        CData/*0:0*/ top__DOT__csrbank4_master_cs0_re;
        CData/*0:0*/ top__DOT__csrbank4_master_cs0_we;
        CData/*0:0*/ top__DOT__csrbank4_master_phyconfig0_re;
        CData/*0:0*/ top__DOT__csrbank4_master_phyconfig0_we;
        CData/*0:0*/ top__DOT__csrbank4_master_status_re;
        CData/*0:0*/ top__DOT__csrbank4_master_status_we;
        CData/*0:0*/ top__DOT__csrbank5_clk_divisor0_re;
        CData/*0:0*/ top__DOT__csrbank5_clk_divisor0_we;
        CData/*0:0*/ top__DOT__csrbank6_load0_re;
        CData/*0:0*/ top__DOT__csrbank6_load0_we;
        CData/*0:0*/ top__DOT__csrbank6_reload0_re;
        CData/*0:0*/ top__DOT__csrbank6_reload0_we;
        CData/*0:0*/ top__DOT__csrbank6_en0_re;
        CData/*0:0*/ top__DOT__csrbank6_en0_we;
        CData/*0:0*/ top__DOT__csrbank6_update_value0_re;
        CData/*0:0*/ top__DOT__csrbank6_update_value0_we;
    };
    struct {
        CData/*0:0*/ top__DOT__csrbank6_value_re;
        CData/*0:0*/ top__DOT__csrbank6_value_we;
        CData/*0:0*/ top__DOT__csrbank6_ev_status_re;
        CData/*0:0*/ top__DOT__csrbank6_ev_status_we;
        CData/*0:0*/ top__DOT__csrbank6_ev_pending_re;
        CData/*0:0*/ top__DOT__csrbank6_ev_pending_we;
        CData/*0:0*/ top__DOT__csrbank6_ev_enable0_re;
        CData/*0:0*/ top__DOT__csrbank6_ev_enable0_we;
        CData/*0:0*/ top__DOT__csrbank7_txfull_re;
        CData/*0:0*/ top__DOT__csrbank7_txfull_we;
        CData/*0:0*/ top__DOT__csrbank7_rxempty_re;
        CData/*0:0*/ top__DOT__csrbank7_rxempty_we;
        CData/*0:0*/ top__DOT__csrbank7_ev_status_re;
        CData/*0:0*/ top__DOT__csrbank7_ev_status_we;
        CData/*0:0*/ top__DOT__csrbank7_ev_pending_re;
        CData/*0:0*/ top__DOT__csrbank7_ev_pending_we;
        CData/*0:0*/ top__DOT__csrbank7_ev_enable0_re;
        CData/*0:0*/ top__DOT__csrbank7_ev_enable0_we;
        CData/*0:0*/ top__DOT__csrbank7_txempty_re;
        CData/*0:0*/ top__DOT__csrbank7_txempty_we;
        CData/*0:0*/ top__DOT__csrbank7_rxfull_re;
        CData/*0:0*/ top__DOT__csrbank7_rxfull_we;
        CData/*0:0*/ top__DOT__csrbank8_out0_re;
        CData/*0:0*/ top__DOT__csrbank8_out0_we;
        CData/*0:0*/ top__DOT__state;
        CData/*0:0*/ top__DOT__next_state;
        CData/*3:0*/ top__DOT__array_muxed2;
        CData/*0:0*/ top__DOT__array_muxed3;
        CData/*0:0*/ top__DOT__array_muxed4;
        CData/*0:0*/ top__DOT__array_muxed5;
        CData/*2:0*/ top__DOT__array_muxed6;
        CData/*1:0*/ top__DOT__array_muxed7;
        CData/*0:0*/ top__DOT__multiregimpl0_regs0;
        CData/*0:0*/ top__DOT__multiregimpl0_regs1;
        CData/*0:0*/ top__DOT__multiregimpl1_regs0;
        CData/*0:0*/ top__DOT__multiregimpl1_regs1;
        CData/*0:0*/ top__DOT__multiregimpl2_regs0;
        CData/*0:0*/ top__DOT__multiregimpl2_regs1;
        CData/*0:0*/ top__DOT__multiregimpl3_regs0;
        CData/*0:0*/ top__DOT__multiregimpl3_regs1;
        CData/*0:0*/ top__DOT__multiregimpl4_regs0;
        CData/*0:0*/ top__DOT__multiregimpl4_regs1;
        CData/*0:0*/ top__DOT__multiregimpl5_regs0;
        CData/*0:0*/ top__DOT__multiregimpl5_regs1;
        CData/*0:0*/ top__DOT__multiregimpl6_regs0;
        CData/*0:0*/ top__DOT__multiregimpl6_regs1;
        CData/*0:0*/ top__DOT__multiregimpl7_regs0;
        CData/*0:0*/ top__DOT__multiregimpl7_regs1;
        CData/*0:0*/ top__DOT__multiregimpl8_regs0;
        CData/*0:0*/ top__DOT__multiregimpl8_regs1;
        CData/*0:0*/ top__DOT__multiregimpl9_regs0;
        CData/*0:0*/ top__DOT__multiregimpl9_regs1;
        CData/*0:0*/ top__DOT__multiregimpl10_regs0;
        CData/*0:0*/ top__DOT__multiregimpl10_regs1;
        CData/*0:0*/ top__DOT__multiregimpl11_regs0;
        CData/*0:0*/ top__DOT__multiregimpl11_regs1;
        CData/*0:0*/ top__DOT__multiregimpl12_regs0;
        CData/*0:0*/ top__DOT__multiregimpl12_regs1;
        CData/*0:0*/ top__DOT__multiregimpl13_regs0;
        CData/*0:0*/ top__DOT__multiregimpl13_regs1;
        CData/*0:0*/ top__DOT__multiregimpl14_regs0;
        CData/*0:0*/ top__DOT__multiregimpl14_regs1;
        CData/*0:0*/ top__DOT__multiregimpl15_regs0;
        CData/*0:0*/ top__DOT__multiregimpl15_regs1;
    };
    struct {
        CData/*0:0*/ top__DOT__multiregimpl16_regs0;
        CData/*0:0*/ top__DOT__multiregimpl16_regs1;
        CData/*0:0*/ top__DOT__multiregimpl17_regs0;
        CData/*0:0*/ top__DOT__multiregimpl17_regs1;
        CData/*0:0*/ top__DOT__multiregimpl18_regs0;
        CData/*0:0*/ top__DOT__multiregimpl18_regs1;
        CData/*0:0*/ top__DOT__multiregimpl19_regs0;
        CData/*0:0*/ top__DOT__multiregimpl19_regs1;
        CData/*0:0*/ top__DOT__multiregimpl20_regs0;
        CData/*0:0*/ top__DOT__multiregimpl20_regs1;
        CData/*0:0*/ top__DOT__multiregimpl21_regs0;
        CData/*0:0*/ top__DOT__multiregimpl21_regs1;
        CData/*0:0*/ top__DOT__multiregimpl22_regs0;
        CData/*0:0*/ top__DOT__multiregimpl22_regs1;
        CData/*0:0*/ top__DOT__multiregimpl23_regs0;
        CData/*0:0*/ top__DOT__multiregimpl23_regs1;
        CData/*0:0*/ top__DOT__multiregimpl24_regs0;
        CData/*0:0*/ top__DOT__multiregimpl24_regs1;
        CData/*0:0*/ top__DOT__multiregimpl25_regs0;
        CData/*0:0*/ top__DOT__multiregimpl25_regs1;
        CData/*0:0*/ top__DOT__multiregimpl26_regs0;
        CData/*0:0*/ top__DOT__multiregimpl26_regs1;
        CData/*0:0*/ top__DOT__multiregimpl27_regs0;
        CData/*0:0*/ top__DOT__multiregimpl27_regs1;
        CData/*0:0*/ top__DOT__multiregimpl28_regs0;
        CData/*0:0*/ top__DOT__multiregimpl28_regs1;
        CData/*0:0*/ top__DOT__multiregimpl29_regs0;
        CData/*0:0*/ top__DOT__multiregimpl29_regs1;
        CData/*0:0*/ top__DOT__multiregimpl30_regs0;
        CData/*0:0*/ top__DOT__multiregimpl30_regs1;
        CData/*0:0*/ top__DOT__multiregimpl31_regs0;
        CData/*0:0*/ top__DOT__multiregimpl31_regs1;
        CData/*0:0*/ top__DOT__multiregimpl32_regs0;
        CData/*0:0*/ top__DOT__multiregimpl32_regs1;
        CData/*0:0*/ top__DOT__multiregimpl33_regs0;
        CData/*0:0*/ top__DOT__multiregimpl33_regs1;
        CData/*0:0*/ top__DOT__multiregimpl34_regs0;
        CData/*0:0*/ top__DOT__multiregimpl34_regs1;
        CData/*0:0*/ top__DOT__multiregimpl35_regs0;
        CData/*0:0*/ top__DOT__multiregimpl35_regs1;
        CData/*0:0*/ top__DOT__multiregimpl36_regs0;
        CData/*0:0*/ top__DOT__multiregimpl36_regs1;
        CData/*0:0*/ top__DOT__multiregimpl37_regs0;
        CData/*0:0*/ top__DOT__multiregimpl37_regs1;
        CData/*0:0*/ top__DOT__multiregimpl38_regs0;
        CData/*0:0*/ top__DOT__multiregimpl38_regs1;
        CData/*0:0*/ top__DOT__multiregimpl39_regs0;
        CData/*0:0*/ top__DOT__multiregimpl39_regs1;
        CData/*0:0*/ top__DOT__multiregimpl40_regs0;
        CData/*0:0*/ top__DOT__multiregimpl40_regs1;
        CData/*0:0*/ top__DOT__multiregimpl41_regs0;
        CData/*0:0*/ top__DOT__multiregimpl41_regs1;
        CData/*0:0*/ top__DOT__multiregimpl42_regs0;
        CData/*0:0*/ top__DOT__multiregimpl42_regs1;
        CData/*0:0*/ top__DOT__multiregimpl43_regs0;
        CData/*0:0*/ top__DOT__multiregimpl43_regs1;
        CData/*0:0*/ top__DOT__multiregimpl44_regs0;
        CData/*0:0*/ top__DOT__multiregimpl44_regs1;
        CData/*0:0*/ top__DOT__multiregimpl45_regs0;
        CData/*0:0*/ top__DOT__multiregimpl45_regs1;
        CData/*0:0*/ top__DOT__multiregimpl46_regs0;
        CData/*0:0*/ top__DOT__multiregimpl46_regs1;
        CData/*0:0*/ top__DOT__multiregimpl47_regs0;
        CData/*0:0*/ top__DOT__multiregimpl47_regs1;
    };
    struct {
        CData/*0:0*/ top__DOT__multiregimpl48_regs0;
        CData/*0:0*/ top__DOT__multiregimpl48_regs1;
        CData/*0:0*/ top__DOT__multiregimpl49_regs0;
        CData/*0:0*/ top__DOT__multiregimpl49_regs1;
        CData/*0:0*/ top__DOT__multiregimpl50_regs0;
        CData/*0:0*/ top__DOT__multiregimpl50_regs1;
        CData/*0:0*/ top__DOT__multiregimpl51_regs0;
        CData/*0:0*/ top__DOT__multiregimpl51_regs1;
        CData/*0:0*/ top__DOT__multiregimpl52_regs0;
        CData/*0:0*/ top__DOT__multiregimpl52_regs1;
        CData/*0:0*/ top__DOT__multiregimpl53_regs0;
        CData/*0:0*/ top__DOT__multiregimpl53_regs1;
        CData/*0:0*/ top__DOT__multiregimpl54_regs0;
        CData/*0:0*/ top__DOT__multiregimpl54_regs1;
        CData/*0:0*/ top__DOT__multiregimpl55_regs0;
        CData/*0:0*/ top__DOT__multiregimpl55_regs1;
        CData/*0:0*/ top__DOT__multiregimpl56_regs0;
        CData/*0:0*/ top__DOT__multiregimpl56_regs1;
        CData/*0:0*/ top__DOT__multiregimpl57_regs0;
        CData/*0:0*/ top__DOT__multiregimpl57_regs1;
        CData/*0:0*/ top__DOT__multiregimpl58_regs0;
        CData/*0:0*/ top__DOT__multiregimpl58_regs1;
        CData/*0:0*/ top__DOT__multiregimpl59_regs0;
        CData/*0:0*/ top__DOT__multiregimpl59_regs1;
        CData/*0:0*/ top__DOT__multiregimpl60_regs0;
        CData/*0:0*/ top__DOT__multiregimpl60_regs1;
        CData/*0:0*/ top__DOT__multiregimpl61_regs0;
        CData/*0:0*/ top__DOT__multiregimpl61_regs1;
        CData/*0:0*/ top__DOT__multiregimpl62_regs0;
        CData/*0:0*/ top__DOT__multiregimpl62_regs1;
        CData/*0:0*/ top__DOT__multiregimpl63_regs0;
        CData/*0:0*/ top__DOT__multiregimpl63_regs1;
        CData/*0:0*/ top__DOT__multiregimpl64_regs0;
        CData/*0:0*/ top__DOT__multiregimpl64_regs1;
        CData/*0:0*/ top__DOT__multiregimpl65_regs0;
        CData/*0:0*/ top__DOT__multiregimpl65_regs1;
        CData/*0:0*/ top__DOT__multiregimpl66_regs0;
        CData/*0:0*/ top__DOT__multiregimpl66_regs1;
        CData/*0:0*/ top__DOT__multiregimpl67_regs0;
        CData/*0:0*/ top__DOT__multiregimpl67_regs1;
        CData/*0:0*/ top__DOT__multiregimpl68_regs0;
        CData/*0:0*/ top__DOT__multiregimpl68_regs1;
        CData/*0:0*/ top__DOT__multiregimpl69_regs0;
        CData/*0:0*/ top__DOT__multiregimpl69_regs1;
        CData/*0:0*/ top__DOT__multiregimpl70_regs0;
        CData/*0:0*/ top__DOT__multiregimpl70_regs1;
        CData/*0:0*/ top__DOT__multiregimpl71_regs0;
        CData/*0:0*/ top__DOT__multiregimpl71_regs1;
        CData/*0:0*/ top__DOT__multiregimpl72_regs0;
        CData/*0:0*/ top__DOT__multiregimpl72_regs1;
        CData/*0:0*/ top__DOT__multiregimpl73_regs0;
        CData/*0:0*/ top__DOT__multiregimpl73_regs1;
        CData/*0:0*/ top__DOT__multiregimpl74_regs0;
        CData/*0:0*/ top__DOT__multiregimpl74_regs1;
        CData/*0:0*/ top__DOT__multiregimpl75_regs0;
        CData/*0:0*/ top__DOT__multiregimpl75_regs1;
        CData/*0:0*/ top__DOT__multiregimpl76_regs0;
        CData/*0:0*/ top__DOT__multiregimpl76_regs1;
        CData/*0:0*/ top__DOT__multiregimpl77_regs0;
        CData/*0:0*/ top__DOT__multiregimpl77_regs1;
        CData/*0:0*/ top__DOT__multiregimpl78_regs0;
        CData/*0:0*/ top__DOT__multiregimpl78_regs1;
        CData/*0:0*/ top__DOT__multiregimpl79_regs0;
        CData/*0:0*/ top__DOT__multiregimpl79_regs1;
    };
    struct {
        CData/*0:0*/ top__DOT__multiregimpl80_regs0;
        CData/*0:0*/ top__DOT__multiregimpl80_regs1;
        CData/*0:0*/ top__DOT__multiregimpl81_regs0;
        CData/*0:0*/ top__DOT__multiregimpl81_regs1;
        CData/*0:0*/ top__DOT__multiregimpl82_regs0;
        CData/*0:0*/ top__DOT__multiregimpl82_regs1;
        CData/*0:0*/ top__DOT__multiregimpl83_regs0;
        CData/*0:0*/ top__DOT__multiregimpl83_regs1;
        CData/*0:0*/ top__DOT__multiregimpl84_regs0;
        CData/*0:0*/ top__DOT__multiregimpl84_regs1;
        CData/*0:0*/ top__DOT__multiregimpl85_regs0;
        CData/*0:0*/ top__DOT__multiregimpl85_regs1;
        CData/*0:0*/ top__DOT__multiregimpl86_regs0;
        CData/*0:0*/ top__DOT__multiregimpl86_regs1;
        CData/*0:0*/ top__DOT__multiregimpl87_regs0;
        CData/*0:0*/ top__DOT__multiregimpl87_regs1;
        CData/*0:0*/ top__DOT__multiregimpl88_regs0;
        CData/*0:0*/ top__DOT__multiregimpl88_regs1;
        CData/*0:0*/ top__DOT__multiregimpl89_regs0;
        CData/*0:0*/ top__DOT__multiregimpl89_regs1;
        CData/*0:0*/ top__DOT__multiregimpl90_regs0;
        CData/*0:0*/ top__DOT__multiregimpl90_regs1;
        CData/*0:0*/ top__DOT__multiregimpl91_regs0;
        CData/*0:0*/ top__DOT__multiregimpl91_regs1;
        CData/*0:0*/ top__DOT__multiregimpl92_regs0;
        CData/*0:0*/ top__DOT__multiregimpl92_regs1;
        CData/*0:0*/ top__DOT__multiregimpl93_regs0;
        CData/*0:0*/ top__DOT__multiregimpl93_regs1;
        CData/*0:0*/ top__DOT__multiregimpl94_regs0;
        CData/*0:0*/ top__DOT__multiregimpl94_regs1;
        CData/*0:0*/ top__DOT__multiregimpl95_regs0;
        CData/*0:0*/ top__DOT__multiregimpl95_regs1;
        CData/*0:0*/ top__DOT__multiregimpl96_regs0;
        CData/*0:0*/ top__DOT__multiregimpl96_regs1;
        CData/*0:0*/ top__DOT__multiregimpl97_regs0;
        CData/*0:0*/ top__DOT__multiregimpl97_regs1;
        CData/*0:0*/ top__DOT__multiregimpl98_regs0;
        CData/*0:0*/ top__DOT__multiregimpl98_regs1;
        CData/*0:0*/ top__DOT__multiregimpl99_regs0;
        CData/*0:0*/ top__DOT__multiregimpl99_regs1;
        CData/*0:0*/ top__DOT__multiregimpl100_regs0;
        CData/*0:0*/ top__DOT__multiregimpl100_regs1;
        CData/*0:0*/ top__DOT__multiregimpl101_regs0;
        CData/*0:0*/ top__DOT__multiregimpl101_regs1;
        CData/*0:0*/ top__DOT__multiregimpl102_regs0;
        CData/*0:0*/ top__DOT__multiregimpl102_regs1;
        CData/*0:0*/ top__DOT__multiregimpl103_regs0;
        CData/*0:0*/ top__DOT__multiregimpl103_regs1;
        CData/*0:0*/ top__DOT__multiregimpl104_regs0;
        CData/*0:0*/ top__DOT__multiregimpl104_regs1;
        CData/*0:0*/ top__DOT__multiregimpl105_regs0;
        CData/*0:0*/ top__DOT__multiregimpl105_regs1;
        CData/*0:0*/ top__DOT__multiregimpl106_regs0;
        CData/*0:0*/ top__DOT__multiregimpl106_regs1;
        CData/*0:0*/ top__DOT__multiregimpl107_regs0;
        CData/*0:0*/ top__DOT__multiregimpl107_regs1;
        CData/*0:0*/ top__DOT__multiregimpl108_regs0;
        CData/*0:0*/ top__DOT__multiregimpl108_regs1;
        CData/*0:0*/ top__DOT__multiregimpl109_regs0;
        CData/*0:0*/ top__DOT__multiregimpl109_regs1;
        CData/*0:0*/ top__DOT__multiregimpl110_regs0;
        CData/*0:0*/ top__DOT__multiregimpl110_regs1;
        CData/*0:0*/ top__DOT__multiregimpl111_regs0;
        CData/*0:0*/ top__DOT__multiregimpl111_regs1;
    };
    struct {
        CData/*0:0*/ top__DOT__multiregimpl112_regs0;
        CData/*0:0*/ top__DOT__multiregimpl112_regs1;
        CData/*0:0*/ top__DOT__multiregimpl113_regs0;
        CData/*0:0*/ top__DOT__multiregimpl113_regs1;
        CData/*0:0*/ top__DOT__multiregimpl114_regs0;
        CData/*0:0*/ top__DOT__multiregimpl114_regs1;
        CData/*0:0*/ top__DOT__multiregimpl115_regs0;
        CData/*0:0*/ top__DOT__multiregimpl115_regs1;
        CData/*0:0*/ top__DOT__multiregimpl116_regs0;
        CData/*0:0*/ top__DOT__multiregimpl116_regs1;
        CData/*0:0*/ top__DOT__multiregimpl117_regs0;
        CData/*0:0*/ top__DOT__multiregimpl117_regs1;
        CData/*0:0*/ top__DOT__multiregimpl118_regs0;
        CData/*0:0*/ top__DOT__multiregimpl118_regs1;
        CData/*0:0*/ top__DOT__multiregimpl119_regs0;
        CData/*0:0*/ top__DOT__multiregimpl119_regs1;
        CData/*0:0*/ top__DOT__multiregimpl120_regs0;
        CData/*0:0*/ top__DOT__multiregimpl120_regs1;
        CData/*0:0*/ top__DOT__multiregimpl121_regs0;
        CData/*0:0*/ top__DOT__multiregimpl121_regs1;
        CData/*0:0*/ top__DOT__multiregimpl122_regs0;
        CData/*0:0*/ top__DOT__multiregimpl122_regs1;
        CData/*0:0*/ top__DOT__multiregimpl123_regs0;
        CData/*0:0*/ top__DOT__multiregimpl123_regs1;
        CData/*0:0*/ top__DOT__multiregimpl124_regs0;
        CData/*0:0*/ top__DOT__multiregimpl124_regs1;
        CData/*0:0*/ top__DOT__multiregimpl125_regs0;
        CData/*0:0*/ top__DOT__multiregimpl125_regs1;
        CData/*0:0*/ top__DOT__multiregimpl126_regs0;
        CData/*0:0*/ top__DOT__multiregimpl126_regs1;
        CData/*0:0*/ top__DOT__multiregimpl127_regs0;
        CData/*0:0*/ top__DOT__multiregimpl127_regs1;
        CData/*0:0*/ top__DOT__multiregimpl128_regs0;
        CData/*0:0*/ top__DOT__multiregimpl128_regs1;
        CData/*0:0*/ top__DOT__multiregimpl129_regs0;
        CData/*0:0*/ top__DOT__multiregimpl129_regs1;
        CData/*0:0*/ top__DOT__multiregimpl130_regs0;
        CData/*0:0*/ top__DOT__multiregimpl130_regs1;
        CData/*0:0*/ top__DOT__picorv32__DOT__trace_valid;
        CData/*4:0*/ top__DOT__picorv32__DOT__reg_sh;
        CData/*0:0*/ top__DOT__picorv32__DOT__irq_delay;
        CData/*0:0*/ top__DOT__picorv32__DOT__irq_active;
        CData/*1:0*/ top__DOT__picorv32__DOT__mem_state;
        CData/*1:0*/ top__DOT__picorv32__DOT__mem_wordsize;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_do_prefetch;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_do_rinst;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_do_rdata;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_do_wdata;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_xfer;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_la_secondword;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_la_firstword_reg;
        CData/*0:0*/ top__DOT__picorv32__DOT__last_mem_valid;
        CData/*0:0*/ top__DOT__picorv32__DOT__prefetched_high_word;
        CData/*0:0*/ top__DOT__picorv32__DOT__clear_prefetched_high_word;
        CData/*0:0*/ top__DOT__picorv32__DOT__mem_done;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_lui;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_auipc;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_jal;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_jalr;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_beq;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_bne;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_blt;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_bge;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_bltu;
    };
    struct {
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_bgeu;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_lb;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_lh;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_lw;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_lbu;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_lhu;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sb;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sh;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sw;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_addi;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_slti;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sltiu;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_xori;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_ori;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_andi;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_slli;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_srli;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_srai;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_add;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sub;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sll;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_slt;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sltu;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_xor;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_srl;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_sra;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_or;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_and;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_rdcycle;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_rdcycleh;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_rdinstr;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_rdinstrh;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_ecall_ebreak;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_getq;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_setq;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_retirq;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_maskirq;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_waitirq;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_timer;
        CData/*0:0*/ top__DOT__picorv32__DOT__instr_trap;
        CData/*5:0*/ top__DOT__picorv32__DOT__decoded_rd;
        CData/*5:0*/ top__DOT__picorv32__DOT__decoded_rs1;
        CData/*5:0*/ top__DOT__picorv32__DOT__decoded_rs2;
        CData/*0:0*/ top__DOT__picorv32__DOT__decoder_trigger;
        CData/*0:0*/ top__DOT__picorv32__DOT__decoder_trigger_q;
        CData/*0:0*/ top__DOT__picorv32__DOT__decoder_pseudo_trigger;
        CData/*0:0*/ top__DOT__picorv32__DOT__decoder_pseudo_trigger_q;
        CData/*0:0*/ top__DOT__picorv32__DOT__compressed_instr;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_lui_auipc_jal;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_slli_srli_srai;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_sb_sh_sw;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_sll_srl_sra;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_slti_blt_slt;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_sltiu_bltu_sltu;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_lbu_lhu_lw;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_alu_reg_imm;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_alu_reg_reg;
        CData/*0:0*/ top__DOT__picorv32__DOT__is_compare;
        CData/*4:0*/ top__DOT__picorv32__DOT__dbg_insn_rs1;
        CData/*4:0*/ top__DOT__picorv32__DOT__dbg_insn_rs2;
    };
    struct {
        CData/*4:0*/ top__DOT__picorv32__DOT__dbg_insn_rd;
        CData/*0:0*/ top__DOT__picorv32__DOT__dbg_rs1val_valid;
        CData/*0:0*/ top__DOT__picorv32__DOT__dbg_rs2val_valid;
        CData/*4:0*/ top__DOT__picorv32__DOT__q_insn_rs1;
        CData/*4:0*/ top__DOT__picorv32__DOT__q_insn_rs2;
        CData/*4:0*/ top__DOT__picorv32__DOT__q_insn_rd;
        CData/*0:0*/ top__DOT__picorv32__DOT__dbg_next;
        CData/*0:0*/ top__DOT__picorv32__DOT__launch_next_insn;
        CData/*0:0*/ top__DOT__picorv32__DOT__dbg_valid_insn;
        CData/*4:0*/ top__DOT__picorv32__DOT__cached_insn_rs1;
        CData/*4:0*/ top__DOT__picorv32__DOT__cached_insn_rs2;
        CData/*4:0*/ top__DOT__picorv32__DOT__cached_insn_rd;
        CData/*7:0*/ top__DOT__picorv32__DOT__cpu_state;
        CData/*1:0*/ top__DOT__picorv32__DOT__irq_state;
        CData/*0:0*/ top__DOT__picorv32__DOT__set_mem_do_rinst;
        CData/*0:0*/ top__DOT__picorv32__DOT__set_mem_do_rdata;
        CData/*0:0*/ top__DOT__picorv32__DOT__set_mem_do_wdata;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_store;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_stalu;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_branch;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_compr;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_trace;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_is_lu;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_is_lh;
        CData/*0:0*/ top__DOT__picorv32__DOT__latched_is_lb;
        CData/*5:0*/ top__DOT__picorv32__DOT__latched_rd;
        CData/*3:0*/ top__DOT__picorv32__DOT__pcpi_timeout_counter;
        CData/*0:0*/ top__DOT__picorv32__DOT__pcpi_timeout;
        CData/*0:0*/ top__DOT__picorv32__DOT__do_waitirq;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_out_0;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_out_0_q;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_wait;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_wait_2;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_eq;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_ltu;
        CData/*0:0*/ top__DOT__picorv32__DOT__alu_lts;
        CData/*0:0*/ top__DOT__picorv32__DOT__clear_prefetched_high_word_q;
        CData/*0:0*/ top__DOT__picorv32__DOT__cpuregs_write;
        SData/*8:0*/ top__DOT__mgmtsoc_litespimmap_count;
        SData/*13:0*/ top__DOT__mgmtsoc_adr;
        SData/*9:0*/ top__DOT__memdat;
        SData/*9:0*/ top__DOT__memdat_1;
        SData/*9:0*/ top__DOT__memdat_2;
        SData/*9:0*/ top__DOT__memdat_3;
        SData/*15:0*/ top__DOT__picorv32__DOT__mem_16bit_buffer;
        IData/*31:0*/ top__DOT__mgmtsoc_scratch_storage;
        IData/*31:0*/ top__DOT__mgmtsoc_bus_errors;
        IData/*31:0*/ top__DOT__mgmtsoc_picorv32_interrupt;
        IData/*31:0*/ top__DOT__mgmtsoc_picorv32_mem_addr;
        IData/*31:0*/ top__DOT__mgmtsoc_picorv32_mem_wdata;
        IData/*31:0*/ top__DOT__mgmtsoc_picorv323;
        IData/*31:0*/ top__DOT__mgmtsoc_picorv326;
        IData/*31:0*/ top__DOT__mgmtsoc_picorv329;
        IData/*31:0*/ top__DOT__mgmtsoc_tx_phase;
        IData/*31:0*/ top__DOT__mgmtsoc_rx_phase;
        IData/*31:0*/ top__DOT__mgmtsoc_timer_load_storage;
        IData/*31:0*/ top__DOT__mgmtsoc_timer_reload_storage;
        IData/*31:0*/ top__DOT__mgmtsoc_timer_value_status;
        IData/*31:0*/ top__DOT__mgmtsoc_timer_value;
        IData/*31:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_out;
        IData/*31:0*/ top__DOT__mgmtsoc_litespisdrphycore_sr_in;
        IData/*31:0*/ top__DOT__mgmtsoc_litespimmap_source_payload_data;
        IData/*31:0*/ top__DOT__mgmtsoc_litespimmap_bus_dat_r;
        IData/*29:0*/ top__DOT__mgmtsoc_litespimmap_burst_adr;
    };
    struct {
        IData/*23:0*/ top__DOT__mgmtsoc_master_phyconfig_storage;
        IData/*31:0*/ top__DOT__mgmtsoc_master_tx_fifo_source_payload_data;
        IData/*31:0*/ top__DOT__mgmtsoc_master_rx_fifo_source_payload_data;
        IData/*31:0*/ top__DOT__uart_bridge_tx_phase;
        IData/*31:0*/ top__DOT__uart_bridge_rx_phase;
        IData/*31:0*/ top__DOT__uart_bridge_address;
        IData/*31:0*/ top__DOT__uart_bridge_data;
        IData/*19:0*/ top__DOT__uart_bridge_count;
        WData/*127:0*/ top__DOT__la_ien_storage[4];
        WData/*127:0*/ top__DOT__la_oe_storage[4];
        WData/*127:0*/ top__DOT__la_in_status[4];
        WData/*127:0*/ top__DOT__la_out_storage[4];
        IData/*31:0*/ top__DOT__litespi_tx_mux_source_payload_data;
        IData/*31:0*/ top__DOT__litespi_rx_demux_endpoint0_source_payload_data;
        IData/*31:0*/ top__DOT__litespi_rx_demux_endpoint1_source_payload_data;
        IData/*29:0*/ top__DOT__mgmtsoc_litespimmap_burst_adr_litespi_next_value1;
        IData/*31:0*/ top__DOT__uart_bridge_address_uartwishbonebridge_next_value4;
        IData/*31:0*/ top__DOT__uart_bridge_data_uartwishbonebridge_next_value6;
        IData/*31:0*/ top__DOT__mgmtsoc_dat_w;
        IData/*31:0*/ top__DOT__mgmtsoc_wishbone_dat_r;
        IData/*31:0*/ top__DOT__shared_dat_r;
        IData/*19:0*/ top__DOT__count;
        IData/*31:0*/ top__DOT__interface0_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface1_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface2_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface3_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface4_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface5_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface6_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface7_bank_bus_dat_r;
        IData/*31:0*/ top__DOT__interface8_bank_bus_dat_r;
        IData/*29:0*/ top__DOT__array_muxed0;
        IData/*31:0*/ top__DOT__array_muxed1;
        IData/*31:0*/ top__DOT__picorv32__DOT__reg_pc;
        IData/*31:0*/ top__DOT__picorv32__DOT__reg_next_pc;
        IData/*31:0*/ top__DOT__picorv32__DOT__reg_op1;
        IData/*31:0*/ top__DOT__picorv32__DOT__reg_op2;
        IData/*31:0*/ top__DOT__picorv32__DOT__reg_out;
        IData/*31:0*/ top__DOT__picorv32__DOT__next_insn_opcode;
        IData/*31:0*/ top__DOT__picorv32__DOT__dbg_insn_opcode;
        IData/*31:0*/ top__DOT__picorv32__DOT__dbg_insn_addr;
        IData/*31:0*/ top__DOT__picorv32__DOT__next_pc;
        IData/*31:0*/ top__DOT__picorv32__DOT__irq_mask;
        IData/*31:0*/ top__DOT__picorv32__DOT__irq_pending;
        IData/*31:0*/ top__DOT__picorv32__DOT__timer;
        IData/*31:0*/ top__DOT__picorv32__DOT__i;
        IData/*31:0*/ top__DOT__picorv32__DOT__mem_rdata_word;
        IData/*31:0*/ top__DOT__picorv32__DOT__mem_rdata_q;
        IData/*31:0*/ top__DOT__picorv32__DOT__mem_rdata_latched_noshuffle;
        IData/*31:0*/ top__DOT__picorv32__DOT__decoded_imm;
        IData/*31:0*/ top__DOT__picorv32__DOT__decoded_imm_j;
        IData/*31:0*/ top__DOT__picorv32__DOT__dbg_insn_imm;
        IData/*31:0*/ top__DOT__picorv32__DOT__dbg_rs1val;
        IData/*31:0*/ top__DOT__picorv32__DOT__dbg_rs2val;
        IData/*31:0*/ top__DOT__picorv32__DOT__q_insn_imm;
        IData/*31:0*/ top__DOT__picorv32__DOT__q_insn_opcode;
        IData/*31:0*/ top__DOT__picorv32__DOT__cached_insn_imm;
        IData/*31:0*/ top__DOT__picorv32__DOT__cached_insn_opcode;
        WData/*127:0*/ top__DOT__picorv32__DOT__dbg_ascii_state[4];
        IData/*31:0*/ top__DOT__picorv32__DOT__current_pc;
        IData/*31:0*/ top__DOT__picorv32__DOT__next_irq_pending;
        IData/*31:0*/ top__DOT__picorv32__DOT__alu_out;
        IData/*31:0*/ top__DOT__picorv32__DOT__alu_out_q;
        IData/*31:0*/ top__DOT__picorv32__DOT__cpuregs_wrdata;
    };
    struct {
        IData/*31:0*/ top__DOT__picorv32__DOT__cpuregs_rs1;
        IData/*31:0*/ top__DOT__picorv32__DOT__cpuregs_rs2;
        QData/*35:0*/ top__DOT__picorv32__DOT__trace_data;
        QData/*63:0*/ top__DOT__picorv32__DOT__count_cycle;
        QData/*63:0*/ top__DOT__picorv32__DOT__count_instr;
        QData/*63:0*/ top__DOT__picorv32__DOT__new_ascii_instr;
        QData/*63:0*/ top__DOT__picorv32__DOT__dbg_ascii_instr;
        QData/*63:0*/ top__DOT__picorv32__DOT__q_ascii_instr;
        QData/*63:0*/ top__DOT__picorv32__DOT__cached_ascii_instr;
        SData/*9:0*/ top__DOT__storage[16];
        SData/*9:0*/ top__DOT__storage_1[16];
        IData/*31:0*/ top__DOT__picorv32__DOT__cpuregs[36];
    };
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    CData/*0:0*/ top__DOT____Vcellinp__picorv32__resetn;
    CData/*7:0*/ __Vtableidx1;
    CData/*1:0*/ __Vdly__top__DOT__picorv32__DOT__mem_state;
    CData/*4:0*/ __Vdly__top__DOT__picorv32__DOT__reg_sh;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__decoder_trigger;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__decoder_pseudo_trigger;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__do_waitirq;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__mem_do_rinst;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__latched_is_lu;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__latched_is_lh;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__latched_is_lb;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__irq_active;
    CData/*5:0*/ __Vdly__top__DOT__picorv32__DOT__latched_rd;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__latched_compr;
    CData/*1:0*/ __Vdly__top__DOT__picorv32__DOT__irq_state;
    CData/*0:0*/ __Vdly__top__DOT__picorv32__DOT__mem_do_prefetch;
    CData/*7:0*/ __Vdly__top__DOT__picorv32__DOT__cpu_state;
    CData/*0:0*/ __Vclklast__TOP__sys_clk;
    IData/*31:0*/ top__DOT__picorv32__DOT____Vlvbound1;
    IData/*31:0*/ __Vdly__top__DOT__mgmtsoc_timer_value;
    IData/*31:0*/ __Vdly__top__DOT__picorv32__DOT__reg_out;
    IData/*31:0*/ __Vdly__top__DOT__picorv32__DOT__reg_pc;
    IData/*31:0*/ __Vdly__top__DOT__picorv32__DOT__reg_op1;
    CData/*0:0*/ __Vm_traceActivity[2];
    static WData/*127:0*/ __Vtable1_top__DOT__picorv32__DOT__dbg_ascii_state[256][4];
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vtop__Syms* __VlSymsp;  // Symbol table
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    Vtop(VerilatedContext* contextp, const char* name = "TOP");
    Vtop(const char* name = "TOP")
      : Vtop(nullptr, name) {}
    /// Destroy the model; called (often implicitly) by application code
    ~Vtop();
    /// Trace signals in the model; called by application code
    void trace(VerilatedVcdC* tfp, int levels, int options = 0);
    
    // API METHODS
    /// Return current simulation context for this model.
    /// Used to get to e.g. simulation time via contextp()->time()
    VerilatedContext* contextp();
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
    static void _eval_initial_loop(Vtop__Syms* __restrict vlSymsp);
    void __Vconfigure(Vtop__Syms* symsp, bool first);
  private:
    static QData _change_request(Vtop__Syms* __restrict vlSymsp);
    static QData _change_request_1(Vtop__Syms* __restrict vlSymsp);
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _eval(Vtop__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__1(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__3(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__4(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__2(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
  private:
    static void traceChgSub0(void* userp, VerilatedVcd* tracep);
    static void traceChgTop0(void* userp, VerilatedVcd* tracep);
    static void traceCleanup(void* userp, VerilatedVcd* /*unused*/);
    static void traceFullSub0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceFullTop0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInitSub0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInitTop(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    void traceRegister(VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
