name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tarball
        run: |
          tar -czf ${{ github.ref_name }}.tar.gz mag def lef openlane/Makefile signoff/*/openlane-signoff/spef verilog LICENSE Makefile
      - name: Upload binaries to release
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ github.ref_name }}.tar.gz
          release-tag: ${{ github.ref }}
